// <auto-generated />
using CosmeticsStore.Repositories.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CosmeticsStore.Repositories.Migrations
{
    [DbContext(typeof(CosmeticsDbContext))]
    [Migration("20260121153328_AddKeyAttributes")]
    partial class AddKeyAttributes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CosmeticsStore.Repositories.Models.CosmeticCategory", b =>
                {
                    b.Property<string>("CategoryId")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("CategoryID");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("FormulationType")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("UsagePurpose")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("CategoryId")
                        .HasName("PK__Cosmetic__19093A2B806C6EC8");

                    b.ToTable("CosmeticCategory", (string)null);
                });

            modelBuilder.Entity("CosmeticsStore.Repositories.Models.CosmeticInformation", b =>
                {
                    b.Property<string>("CosmeticId")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("CosmeticID");

                    b.Property<string>("CategoryId")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("CategoryID");

                    b.Property<string>("CosmeticName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("CosmeticSize")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<decimal>("DollarPrice")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("ExpirationDate")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("SkinType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("CosmeticId")
                        .HasName("PK__Cosmetic__98ED527EE44B0CFB");

                    b.HasIndex("CategoryId");

                    b.ToTable("CosmeticInformation", (string)null);
                });

            modelBuilder.Entity("CosmeticsStore.Repositories.Models.SystemAccount", b =>
                {
                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("AccountID");

                    b.Property<string>("AccountNote")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)");

                    b.Property<string>("AccountPassword")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Role")
                        .HasColumnType("int");

                    b.HasKey("AccountId")
                        .HasName("PK__SystemAc__349DA5861F02AFCD");

                    b.HasIndex(new[] { "EmailAddress" }, "UQ__SystemAc__49A147406F942315")
                        .IsUnique()
                        .HasFilter("[EmailAddress] IS NOT NULL");

                    b.ToTable("SystemAccount", (string)null);
                });

            modelBuilder.Entity("CosmeticsStore.Repositories.Models.CosmeticInformation", b =>
                {
                    b.HasOne("CosmeticsStore.Repositories.Models.CosmeticCategory", "Category")
                        .WithMany("CosmeticInformations")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__CosmeticI__Categ__3C69FB99");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CosmeticsStore.Repositories.Models.CosmeticCategory", b =>
                {
                    b.Navigation("CosmeticInformations");
                });
#pragma warning restore 612, 618
        }
    }
}
